#####################
# BASICS
site_name: Swerve Robotics
site_url: https://swerverobotics.github.io
markdown_extensions:
    - smarty
    - meta
    - attr_list

#####################
# NAV 
nav:
- Home: index.md
- About: about.md
- Teams:
    - FTC: teams/teams_ftc.md
    - FLLC: teams/teams_fllc.md
    - FLLE: teams/teams_flle.md
- News:
    - Swerve Returning to Botswana: news/2023_02_botswana.md
- Events: events.md
- Contact Us: contact.md
- Training:
    - Training Grounds: training/training.md
    - Eukota: training/eukota.md
    - FISH: training/innaias (fish).md 


#####################
# THEME
theme:
    name: material
    logo: assets/images/Swerve-Robotics-Logo-1024x289-1.png
    #custom_dir: docs/material

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml, necessary for github pages deployment
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/swerve-favicon32x32.png
    icon:
        logo: logo
    # The palettes need to be in reverse order (blue-pink-green-purple)
    # so they display in the correct order (purple-green-pink-blue)
    palette:
        - scheme: default 
          primary: blue
          toggle:
            icon: material/infinity
            name: "8923 TWIST theme"
        - scheme: default 
          primary: pink
          toggle:
            icon: material/google-downasaur
            name: "6220 DRIFT theme"
        - scheme: default 
          primary: green
          toggle:
            icon:  material/koala
            name: "417 SKID theme"
        - scheme: default
          primary: deep purple
          accent: green
          toggle:
              icon: fontawesome/solid/robot
              name: "Swerve Robotics theme"

    # Additional Values
    features:
        - navigation.instant
        - navigation.tracking
        - toc.follow
        #- toc.integrate
        - navigation.top

#####################
# EXTRAS
use_directory_urls: false # enabled the direct html link for the Guntley PV Barn
extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/swerve-robotics/
        - icon: fontawesome/brands/github
          link: https://github.com/swerverobotics/

#####################
# PLUGINS
plugins:
    - search
